# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ramir\Desktop\JCN\jcn\widgets\carreraW.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import utils


class Ui_carreraW(object):
    def setupUi(self, carreraW):

        carreraW.setObjectName("carreraW")
        carreraW.setEnabled(True)
        carreraW.resize(350, 120)
        carreraW.setMinimumSize(QtCore.QSize(250, 100))
        carreraW.setMaximumSize(QtCore.QSize(350, 150))

        self.label = QtWidgets.QLabel(carreraW)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 41))

        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)

        self.label.setFont(font)
        self.label.setObjectName("label")

        self.line = QtWidgets.QFrame(carreraW)
        self.line.setGeometry(QtCore.QRect(160, 0, 20, 151))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.label_2 = QtWidgets.QLabel(carreraW)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 161, 41))

        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)

        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        self.creaBtt = QtWidgets.QPushButton(carreraW)
        self.creaBtt.setGeometry(QtCore.QRect(40, 60, 75, 23))
        self.creaBtt.setObjectName("creaBtt")
        self.creaBtt.clicked.connect(self.buscaCarrera)
        
        self.buscaL = QtWidgets.QLineEdit(carreraW)
        self.buscaL.setGeometry(QtCore.QRect(200, 50, 121, 20))
        self.buscaL.setPlaceholderText("Ingrese un numero de carrera")
        self.buscaL.setMaxLength(2)
        self.buscaL.setValidator(QtGui.QIntValidator())
        self.buscaL.setObjectName("buscaL")
        self.buscaL.returnPressed.connect(self.buscaCarrera)

        self.buscaBtt = QtWidgets.QPushButton(carreraW)
        self.buscaBtt.setGeometry(QtCore.QRect(220, 80, 75, 23))
        self.buscaBtt.setObjectName("buscaBtt")
        self.buscaBtt.clicked.connect(self.buscaCarrera)

        self.retranslateUi(carreraW)
        QtCore.QMetaObject.connectSlotsByName(carreraW)

    
    def retranslateUi(self, carreraW):
        _translate = QtCore.QCoreApplication.translate
        carreraW.setWindowTitle(_translate("carreraW", "Form"))
        self.creaBtt.setText(_translate("carreraW", "Crear"))
        self.label.setText(_translate("carreraW", "Crear Nueva Carrera"))
        self.label_2.setText(_translate("carreraW", "Abrir Carrera Existente"))
        self.buscaBtt.setText(_translate("carreraW", "Buscar"))


    def buscaCarrera(self):
        sess = utils.bd()
        ncrr = int(self.buscaL.text())
        lng = sess.execute("SELECT COUNT(*) FROM carrera").scalar()
        if lng < ncrr:
            rnn = None
        else:
            rnn = sess.execute("SELECT numero FROM carrera WHERE numero = :val", {'val' : ncrr})
            rnn = rnn.fetchone()
            rnn = rnn['numero']
        return rnn

    def creaCarrera(self):
        #debe recibir nrnn para ingresar la fk
        sess = utils.bd()
        ncrr = sess.execute("SELECT COUNT(*) FROM carrera").scalar()
        sess.execute("INSERT INTO carrera(numero, hora, nroReunion) VALUES (:val, '12:30', 'nroReunion')", {'val' : ncrr+1})
        sess.commit()
        return ncrr

