# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\rcardozo\Desktop\Algo\widgets\reunionW.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
sys.path.append("./")
import utils
from widgets.Ui_carreraW import Ui_carreraW

class Ui_reunionW(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    #Atributos
    nroReunion = None

    def setupUi(self, reunionW):
        reunionW.setObjectName("reunionW")
        reunionW.setEnabled(True)
        reunionW.resize(350, 120)
        reunionW.setMinimumSize(QtCore.QSize(250, 100))
        reunionW.setMaximumSize(QtCore.QSize(350, 150))
        
        self.label = QtWidgets.QLabel(reunionW)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        self.line = QtWidgets.QFrame(reunionW)
        self.line.setGeometry(QtCore.QRect(160, 0, 20, 151))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        
        self.label_2 = QtWidgets.QLabel(reunionW)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        #Boton de Crear
        self.creaBtt = QtWidgets.QPushButton(reunionW)
        self.creaBtt.setGeometry(QtCore.QRect(40, 60, 75, 23))
        self.creaBtt.setObjectName("creaBtt")
        self.creaBtt.clicked.connect(self.creaReunion)
        self.wCarrera = None
        self.creaBtt.clicked.connect(self.goCarrera)
        self.creaBtt.clicked.connect(self.close)
        #Linea de Buscar
        self.buscaL = QtWidgets.QLineEdit(reunionW)
        self.buscaL.setGeometry(QtCore.QRect(200, 50, 121, 20))
        self.buscaL.setPlaceholderText("Ingrese un numero de reunión")
        self.buscaL.setMaxLength(2)
        self.buscaL.setValidator(QtGui.QIntValidator())
        self.buscaL.setObjectName("buscaL")
        self.buscaL.returnPressed.connect(self.buscaReunion)
        #Boton de Buscar
        self.buscaBtt = QtWidgets.QPushButton(reunionW)
        self.buscaBtt.setGeometry(QtCore.QRect(220, 80, 75, 23))
        self.buscaBtt.setObjectName("buscaBtt")
        self.buscaBtt.clicked.connect(self.buscaReunion)

        self.retranslateUi(reunionW)
        QtCore.QMetaObject.connectSlotsByName(reunionW)

    def retranslateUi(self, reunionW):
        _translate = QtCore.QCoreApplication.translate
        reunionW.setWindowTitle(_translate("reunionW", "Form"))
        self.creaBtt.setText(_translate("reunionW", "Crear"))
        self.label.setText(_translate("reunionW", "Crear Nueva Reunion"))
        self.label_2.setText(_translate("reunionW", "Abrir Reunion Existente"))
        self.buscaBtt.setText(_translate("reunionW", "Buscar"))

    def creaReunion(self):
        #utilizar esa funcion para pasar al widget de carrera pasando la nrnn
        sess = utils.bd()
        nrnn = sess.execute("SELECT COUNT(*) FROM reunion").scalar()
        sess.execute("INSERT INTO reunion(numero, nombre) VALUES (:val, 'qwerty')", {'val' : nrnn+1})
        sess.commit()
        return nrnn

    def buscaReunion(self):
        sess = utils.bd()
        param = int(self.buscaL.text())
        lng = sess.execute("SELECT COUNT(*) FROM reunion").scalar()
        if lng < param:
            pass
        else:
            rnn = sess.execute("SELECT numero FROM reunion WHERE numero = :val", {'val' : param})
            rnn = rnn.fetchone()
            rnn = rnn['numero']
        self.nroReunion = rnn

    def goCarrera(self):
        if self.wCarrera is None:
            self.wCarrera = Ui_carreraW()
        self.wCarrera.show()
        
        


