# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\rcardozo\Desktop\Algo\widgets\reunionW.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
sys.path.append("./")
#import handle
#import utils

class Ui_reunionW(object):
    def setupUi(self, reunionW):
        reunionW.setObjectName("reunionW")
        reunionW.setEnabled(True)
        reunionW.resize(350, 120)
        reunionW.setMinimumSize(QtCore.QSize(250, 100))
        reunionW.setMaximumSize(QtCore.QSize(350, 150))
        
        self.creaBtt = QtWidgets.QPushButton(reunionW)
        self.creaBtt.setGeometry(QtCore.QRect(40, 80, 75, 23))
        self.creaBtt.setObjectName("creaBtt")
        
        self.label = QtWidgets.QLabel(reunionW)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        self.line = QtWidgets.QFrame(reunionW)
        self.line.setGeometry(QtCore.QRect(160, 0, 20, 151))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        
        self.label_2 = QtWidgets.QLabel(reunionW)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        self.creaL = QtWidgets.QLineEdit(reunionW)
        self.creaL.setGeometry(QtCore.QRect(20, 50, 121, 20))
        self.creaL.setPlaceholderText("Ingrese un numero de reunión")
        self.creaL.setMaxLength(2)
        self.creaL.setValidator(QtGui.QIntValidator())
        self.creaL.setObjectName("creaL")
        
        self.buscaL = QtWidgets.QLineEdit(reunionW)
        self.buscaL.setGeometry(QtCore.QRect(200, 50, 121, 20))
        self.creaL.setPlaceholderText("Ingrese un numero de reunión")
        self.creaL.setMaxLength(2)
        self.creaL.setValidator(QtGui.QIntValidator())
        self.buscaL.setObjectName("buscaL")
        
        self.buscaBtt = QtWidgets.QPushButton(reunionW)
        self.buscaBtt.setGeometry(QtCore.QRect(220, 80, 75, 23))
        self.buscaBtt.setObjectName("buscaBtt")

        self.retranslateUi(reunionW)
        QtCore.QMetaObject.connectSlotsByName(reunionW)

        
        self.buscaL.returnPressed.connect(self.buscaReunion)

        

    def retranslateUi(self, reunionW):
        _translate = QtCore.QCoreApplication.translate
        reunionW.setWindowTitle(_translate("reunionW", "Form"))
        self.creaBtt.setText(_translate("reunionW", "Crear"))
        self.label.setText(_translate("reunionW", "Crear Nueva Reunion"))
        self.label_2.setText(_translate("reunionW", "Abrir Reunion Existente"))
        self.buscaBtt.setText(_translate("reunionW", "Buscar"))

    def getNrnn(self):
        self.nrnn = str(self.creaL.text())
        return self.nrnn

    def buscaReunion(self):
        #sess = utils.bd()
        #self.nrnn = str(self.creaL.text())
        #rnn = sess.execute("SELECT id FROM reunion WHERE id = :val", {'val' : self.nrnn})
        print('holi')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_reunionW()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())