# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\rcardozo\Desktop\Algo\widgets\reunionW.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
sys.path.append("./")
import utils
import datetime
from widgets.Singleton import *


#WidgetReunion
class Wreunion(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    db = Singleton()

    def setupUi(self, reunionW):
        reunionW.setObjectName("reunionW")
        reunionW.setEnabled(True)
        reunionW.resize(350, 120)
        reunionW.setMinimumSize(QtCore.QSize(250, 100))
        reunionW.setMaximumSize(QtCore.QSize(350, 150))
        
        self.label = QtWidgets.QLabel(reunionW)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        self.line = QtWidgets.QFrame(reunionW)
        self.line.setGeometry(QtCore.QRect(160, 0, 20, 151))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.label_2 = QtWidgets.QLabel(reunionW)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        #Boton de Crear
        self.creaBtt = QtWidgets.QPushButton(reunionW)
        self.creaBtt.setGeometry(QtCore.QRect(40, 60, 75, 23))
        self.creaBtt.setObjectName("creaBtt")
        self.wCarrera = None
        self.creaBtt.clicked.connect(self.creaReunion)
        self.creaBtt.clicked.connect(self.close)
        #Combo de Seleccion
        self.buscaC = self.listaReunion()
        self.buscaC.setGeometry(QtCore.QRect(200, 60, 121, 20))
        self.buscaC.activated[str].connect(self.seleccion)
        self.buscaC.activated.connect(self.goCarrera)
        self.buscaC.activated.connect(self.close)
        
        self.retranslateUi(reunionW)
        QtCore.QMetaObject.connectSlotsByName(reunionW)

    def retranslateUi(self, reunionW):
        _translate = QtCore.QCoreApplication.translate
        reunionW.setWindowTitle(_translate("reunionW", "Form"))
        self.creaBtt.setText(_translate("reunionW", "Crear"))
        self.label.setText(_translate("reunionW", "Crear Nueva Reunion"))
        self.label_2.setText(_translate("reunionW", "Seleccionar Reunion"))
        #self.buscaBtt.setText(_translate("reunionW", "Buscar"))

    def creaReunion(self):
        sess = utils.bd()
        nrnn = sess.execute("SELECT COUNT(*) FROM reunion").scalar() + 1
        fec = datetime.date.today()
        sess.execute("INSERT INTO reunion(id, fecha) VALUES (:val, :par)", {'val' : nrnn, 'par' : fec})
        sess.commit()
        sess.close()
        self.db.reunion = nrnn
        self.goCarrera()

    def listaReunion(self):
        sess = utils.bd()
        i = sess.execute("SELECT COUNT(*) FROM reunion").scalar()
        combo = QtWidgets.QComboBox(self)
        combo.setPlaceholderText("None")
        while(0<i):
            query = sess.execute("SELECT * FROM reunion WHERE id = :val", {'val' : i})
            query = query.fetchone()
            reuFec = query['fecha']
            combo.addItem(reuFec)
            i-=1
        sess.close()
        return combo

    def seleccion(self, text):
        sess = utils.bd()
        self.db.reunion = sess.execute("SELECT id FROM reunion WHERE fecha=:val", {'val' : text}).scalar()
        sess.close()


    def goCarrera(self):
        if self.wCarrera is None:
            self.wCarrera = Wcarrera()
        self.wCarrera.show()



#Widget Carrera
class Wcarrera(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        print(Singleton.reunion)

    #Atributos
    nroReunion = Singleton.reunion
    db = Singleton()

    def setupUi(self, carreraW):

        carreraW.setObjectName("carreraW")
        carreraW.setEnabled(True)
        carreraW.resize(350, 120)
        carreraW.setMinimumSize(QtCore.QSize(250, 100))
        carreraW.setMaximumSize(QtCore.QSize(350, 150))

        self.label = QtWidgets.QLabel(carreraW)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.line = QtWidgets.QFrame(carreraW)
        self.line.setGeometry(QtCore.QRect(160, 0, 20, 151))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.label_2 = QtWidgets.QLabel(carreraW)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        #Boton de Crear
        self.creaBtt = QtWidgets.QPushButton(carreraW)
        self.creaBtt.setGeometry(QtCore.QRect(40, 60, 75, 23))
        self.creaBtt.setObjectName("creaBtt")
        self.creaBtt.clicked.connect(self.creaCarrera)
        self.creaBtt.clicked.connect(self.close)
        #Combo de Buscar
        self.buscaC = self.listaCarrera()
        self.buscaC.setGeometry(QtCore.QRect(200, 60, 121, 20))
        self.buscaC.activated[str].connect(self.seleccion)
        self.buscaC.activated.connect(self.close)

        self.retranslateUi(carreraW)
        QtCore.QMetaObject.connectSlotsByName(carreraW)

    def retranslateUi(self, carreraW):
        _translate = QtCore.QCoreApplication.translate
        carreraW.setWindowTitle(_translate("carreraW", "Form"))
        self.creaBtt.setText(_translate("carreraW", "Crear"))
        self.label.setText(_translate("carreraW", "Crear Nueva Carrera"))
        self.label_2.setText(_translate("carreraW", "Abrir Carrera Existente"))


    def creaCarrera(self):
        sess = utils.bd()
        ncrr = sess.execute("SELECT COUNT(*) FROM carrera WHERE idReunion = :val", {'val' : self.nroReunion}).scalar() + 1
        self.db.carrera = sess.execute("SELECT COUNT(*) FROM carrera").scalar() + 1
        sess.execute("INSERT INTO carrera(id, idReunion, numero) VALUES (:val, :par, :var)", {'val' : self.db.carrera, 'par' : self.nroReunion, 'var' : ncrr})
        sess.commit()
        sess.close()

    def listaCarrera(self):
        sess = utils.bd()
        j = sess.execute("SELECT COUNT(*) FROM carrera WHERE idReunion = :val", {'val' : self.nroReunion}).scalar()
        combo = QtWidgets.QComboBox(self)
        combo.setPlaceholderText("None")
        while(0<j):
            query = sess.execute("SELECT * FROM carrera WHERE id = :val", {'val' : j})
            query = query.fetchone()
            carNum = query['numero']
            combo.addItem(carNum)
            j-=1
        sess.close()
        return combo

    def seleccion(self, text):
        sess = utils.bd()
        self.db.carrera = sess.execute("SELECT id FROM carrera WHERE idReunion = :val AND numero=:par", {'val' : self.nroReunion, 'par' : text}).scalar()
        sess.close()


