from PyQt5 import QtCore, QtGui, QtWidgets
from widgets.Wbarra import *

class Ui_MainWindow(QtWidgets.QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        #Box de Carga
        self.bcarga = QtWidgets.QGroupBox(self.centralwidget)
        self.bcarga.setGeometry(QtCore.QRect(10, 10, 221, 561))
        self.bcarga.setTitle("")
        self.bcarga.setObjectName("bcarga")
        
        #Lineas
        self.lines = []
        i = 0
        h = 40
        while(i<16):
            self.lines.append(QtWidgets.QLineEdit(self.bcarga))
            self.lines[i].setGeometry(QtCore.QRect(110, h, 101, 20))
            self.lines[i].setObjectName('line{}'.format(i))
            self.lines[i].setValidator(QtGui.QIntValidator())
            i+=1
            h+=30

        #Labels
        self.label_18 = QtWidgets.QLabel(self.bcarga)
        self.label_18.setGeometry(QtCore.QRect(70, 490, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_5 = QtWidgets.QLabel(self.bcarga)
        self.label_5.setGeometry(QtCore.QRect(80, 100, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.bcarga)
        self.label_6.setGeometry(QtCore.QRect(80, 160, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.bcarga)
        self.label_10.setGeometry(QtCore.QRect(80, 250, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_3 = QtWidgets.QLabel(self.bcarga)
        self.label_3.setGeometry(QtCore.QRect(80, 40, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.bcarga)
        self.label_4.setGeometry(QtCore.QRect(80, 70, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.bcarga)
        self.label_8.setGeometry(QtCore.QRect(80, 130, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(self.bcarga)
        self.label_2.setGeometry(QtCore.QRect(120, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_13 = QtWidgets.QLabel(self.bcarga)
        self.label_13.setGeometry(QtCore.QRect(80, 220, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_11 = QtWidgets.QLabel(self.bcarga)
        self.label_11.setGeometry(QtCore.QRect(80, 280, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_16 = QtWidgets.QLabel(self.bcarga)
        self.label_16.setGeometry(QtCore.QRect(70, 430, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_12 = QtWidgets.QLabel(self.bcarga)
        self.label_12.setGeometry(QtCore.QRect(70, 370, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_7 = QtWidgets.QLabel(self.bcarga)
        self.label_7.setGeometry(QtCore.QRect(80, 190, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.caballos = QtWidgets.QLabel(self.bcarga)
        self.caballos.setGeometry(QtCore.QRect(10, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.caballos.setFont(font)
        self.caballos.setObjectName("caballos")
        self.label_15 = QtWidgets.QLabel(self.bcarga)
        self.label_15.setGeometry(QtCore.QRect(70, 460, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_9 = QtWidgets.QLabel(self.bcarga)
        self.label_9.setGeometry(QtCore.QRect(70, 340, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_17 = QtWidgets.QLabel(self.bcarga)
        self.label_17.setGeometry(QtCore.QRect(70, 400, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_14 = QtWidgets.QLabel(self.bcarga)
        self.label_14.setGeometry(QtCore.QRect(70, 310, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        #Deco
        self.line = QtWidgets.QFrame(self.bcarga)
        self.line.setGeometry(QtCore.QRect(90, 0, 20, 520))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.bcarga)
        self.line_2.setGeometry(QtCore.QRect(0, 510, 221, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        #Boton Descartar
        self.descartar = QtWidgets.QPushButton(self.bcarga)
        self.descartar.setGeometry(QtCore.QRect(0, 530, 101, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.descartar.setFont(font)
        self.descartar.setObjectName("descartar")
        #Boton Guardar
        self.guardar = QtWidgets.QPushButton(self.bcarga)
        self.guardar.setGeometry(QtCore.QRect(110, 530, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.guardar.setFont(font)
        self.guardar.setCheckable(False)
        self.guardar.setObjectName("guardar")
        #Box Carrera
        self.bcarrera = QtWidgets.QGroupBox(self.centralwidget)
        self.bcarrera.setGeometry(QtCore.QRect(490, 0, 101, 51))
        self.bcarrera.setObjectName("bcarrera")
        self.lcarrera = QtWidgets.QLabel(self.bcarrera)
        self.lcarrera.setGeometry(QtCore.QRect(30, 20, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lcarrera.setFont(font)
        self.lcarrera.setAlignment(QtCore.Qt.AlignCenter)
        self.lcarrera.setObjectName("lcarrera")
        #Box Remate
        self.bremate = QtWidgets.QGroupBox(self.centralwidget)
        self.bremate.setGeometry(QtCore.QRect(240, 0, 251, 51))
        self.bremate.setObjectName("bremate")
        self.lremate = QtWidgets.QLineEdit(self.bremate)
        self.lremate.setGeometry(QtCore.QRect(10, 20, 231, 20))
        self.lremate.setObjectName("lremate")
        #Box Porcentajes
        self.porcentajes = QtWidgets.QGroupBox(self.centralwidget)
        self.porcentajes.setGeometry(QtCore.QRect(240, 50, 91, 111))
        self.porcentajes.setObjectName("porcentajes")
        self.diezP = QtWidgets.QRadioButton(self.porcentajes)
        self.diezP.setGeometry(QtCore.QRect(20, 20, 65, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.diezP.setFont(font)
        self.diezP.setChecked(False)
        self.diezP.setAutoRepeat(False)
        self.diezP.setObjectName("diezP")
        self.veinteP = QtWidgets.QRadioButton(self.porcentajes)
        self.veinteP.setGeometry(QtCore.QRect(20, 50, 65, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.veinteP.setFont(font)
        self.veinteP.setChecked(False)
        self.veinteP.setAutoRepeat(False)
        self.veinteP.setObjectName("veinteP")
        self.treintaP = QtWidgets.QRadioButton(self.porcentajes)
        self.treintaP.setGeometry(QtCore.QRect(20, 80, 65, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.treintaP.setFont(font)
        self.treintaP.setChecked(False)
        self.treintaP.setAutoRepeat(False)
        self.treintaP.setObjectName("treintaP")
        #Box Subtotales
        self.bsubtotales = QtWidgets.QGroupBox(self.centralwidget)
        self.bsubtotales.setGeometry(QtCore.QRect(340, 50, 251, 111))
        self.bsubtotales.setObjectName("bsubtotales")
        self.subtotales = QtWidgets.QTextBrowser(self.bsubtotales)
        self.subtotales.setGeometry(QtCore.QRect(10, 20, 231, 81))
        self.subtotales.setObjectName("subtotales")
        #Box Historial
        self.bhistorial = QtWidgets.QGroupBox(self.centralwidget)
        self.bhistorial.setGeometry(QtCore.QRect(240, 170, 351, 401))
        self.bhistorial.setObjectName("bhistorial")
        self.whistorial = QtWidgets.QWidget(self.bhistorial)
        self.whistorial.setGeometry(QtCore.QRect(10, 20, 331, 371))
        self.whistorial.setObjectName("whistorial")
        self.pdfHistorial = QtWidgets.QTextBrowser(self.whistorial)
        self.pdfHistorial.setGeometry(QtCore.QRect(0, 0, 331, 371))
        self.pdfHistorial.setObjectName("pdfHistorial")
        MainWindow.setCentralWidget(self.centralwidget)
        #Barra Superior
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuMen = QtWidgets.QMenu(self.menuBar)
        self.menuMen.setObjectName("menuMen")
        self.menuAcciones = QtWidgets.QMenu(self.menuBar)
        self.menuAcciones.setObjectName("menuAcciones")
        self.menuEdici_n = QtWidgets.QMenu(self.menuBar)
        self.menuEdici_n.setObjectName("menuEdici_n")
        MainWindow.setMenuBar(self.menuBar)
        #Action Reunion
        self.wReunion = None
        self.actionReuniones = QtWidgets.QAction(MainWindow)
        self.actionReuniones.setObjectName("actionReuniones")
        self.actionReuniones.triggered.connect(self.selecReunion)
        #Action Carrera
        self.wCarrera = None
        self.actionCarreras = QtWidgets.QAction(MainWindow)
        self.actionCarreras.setObjectName("actionCarreras")
        self.actionCarreras.triggered.connect(self.selecCarrera)
        
        self.actionRemates = QtWidgets.QAction(MainWindow)
        self.actionRemates.setObjectName("actionRemates")
        self.actionCaballos = QtWidgets.QAction(MainWindow)
        self.actionCaballos.setObjectName("actionCaballos")
        self.actionImprimir_remates = QtWidgets.QAction(MainWindow)
        self.actionImprimir_remates.setObjectName("actionImprimir_remates")
        self.actionImprimir_Carrera = QtWidgets.QAction(MainWindow)
        self.actionImprimir_Carrera.setObjectName("actionImprimir_Carrera")
        self.actionImprimir_Reuni_n = QtWidgets.QAction(MainWindow)
        self.actionImprimir_Reuni_n.setObjectName("actionImprimir_Reuni_n")
        self.actionEditar_Remate = QtWidgets.QAction(MainWindow)
        self.actionEditar_Remate.setObjectName("actionEditar_Remate")
        self.actionEliminar_Caballo = QtWidgets.QAction(MainWindow)
        self.actionEliminar_Caballo.setObjectName("actionEliminar_Caballo")
        self.actionEliminar_Carrera = QtWidgets.QAction(MainWindow)
        self.actionEliminar_Carrera.setObjectName("actionEliminar_Carrera")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionSalir.triggered.connect(self.close)
        self.menuMen.addAction(self.actionReuniones)
        self.menuMen.addAction(self.actionCarreras)
        self.menuMen.addAction(self.actionSalir)
        self.menuAcciones.addAction(self.actionImprimir_remates)
        self.menuAcciones.addAction(self.actionImprimir_Carrera)
        self.menuAcciones.addAction(self.actionImprimir_Reuni_n)
        self.menuEdici_n.addAction(self.actionEditar_Remate)
        self.menuEdici_n.addAction(self.actionEliminar_Caballo)
        self.menuEdici_n.addAction(self.actionEliminar_Carrera)
        self.menuBar.addAction(self.menuMen.menuAction())
        self.menuBar.addAction(self.menuAcciones.menuAction())
        self.menuBar.addAction(self.menuEdici_n.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        MainWindow.setTabOrder(self.guardar, self.descartar)
        MainWindow.setTabOrder(self.descartar, self.diezP)
        MainWindow.setTabOrder(self.diezP, self.veinteP)
        MainWindow.setTabOrder(self.veinteP, self.treintaP)
        MainWindow.setTabOrder(self.treintaP, self.subtotales)
        MainWindow.setTabOrder(self.subtotales, self.pdfHistorial)

        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_18.setText(_translate("MainWindow", "16"))
        self.label_5.setText(_translate("MainWindow", "3"))
        self.label_6.setText(_translate("MainWindow", "5"))
        self.label_10.setText(_translate("MainWindow", "8"))
        self.label_3.setText(_translate("MainWindow", "1"))
        self.label_4.setText(_translate("MainWindow", "2"))
        self.label_8.setText(_translate("MainWindow", "4"))
        self.label_2.setText(_translate("MainWindow", "Montos"))
        self.label_13.setText(_translate("MainWindow", "7"))
        self.label_11.setText(_translate("MainWindow", "9"))
        self.label_16.setText(_translate("MainWindow", "14"))
        self.label_12.setText(_translate("MainWindow", "12"))
        self.label_7.setText(_translate("MainWindow", "6"))
        self.caballos.setText(_translate("MainWindow", "Caballos"))
        self.label_15.setText(_translate("MainWindow", "15"))
        self.label_9.setText(_translate("MainWindow", "11"))
        self.label_17.setText(_translate("MainWindow", "13"))
        self.label_14.setText(_translate("MainWindow", "10"))
        self.descartar.setText(_translate("MainWindow", "Descartar"))
        self.guardar.setText(_translate("MainWindow", "Guardar"))
        self.bcarrera.setTitle(_translate("MainWindow", "Carrera"))
        self.lcarrera.setText(_translate("MainWindow", "XY"))
        self.bremate.setTitle(_translate("MainWindow", "Remate "))
        self.porcentajes.setTitle(_translate("MainWindow", "Porcentaje"))
        self.diezP.setText(_translate("MainWindow", "10%"))
        self.veinteP.setText(_translate("MainWindow", "20%"))
        self.treintaP.setText(_translate("MainWindow", "30%"))
        self.bsubtotales.setTitle(_translate("MainWindow", "Subtotales"))
        self.subtotales.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Recaudado        $var</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">A Pagar        $var</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">A Rendir        $var</span></p></body></html>"))
        self.bhistorial.setTitle(_translate("MainWindow", "Historial de Carga"))
        self.menuMen.setTitle(_translate("MainWindow", "Parámetros"))
        self.menuAcciones.setTitle(_translate("MainWindow", "Impresiones"))
        self.menuEdici_n.setTitle(_translate("MainWindow", "Edición"))
        self.actionReuniones.setText(_translate("MainWindow", "Seleccionar Reunión"))
        self.actionCarreras.setText(_translate("MainWindow", "Seleccionar Carrera"))
        self.actionRemates.setText(_translate("MainWindow", "Remates"))
        self.actionCaballos.setText(_translate("MainWindow", "Caballos"))
        self.actionImprimir_remates.setText(_translate("MainWindow", "Imprimir Remate"))
        self.actionImprimir_Carrera.setText(_translate("MainWindow", "Imprimir Carrera"))
        self.actionImprimir_Reuni_n.setText(_translate("MainWindow", "Imprimir Reunión"))
        self.actionEditar_Remate.setText(_translate("MainWindow", "Editar Remate"))
        self.actionEliminar_Caballo.setText(_translate("MainWindow", "Eliminar Caballo"))
        self.actionEliminar_Carrera.setText(_translate("MainWindow", "Eliminar Carrera"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))

    #Metodos
    
    def closeEvent(self, event):
        close = QtWidgets.QMessageBox.question(self, "Cerrar", "¿Seguro que quiere salir?", QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
        if close == QtWidgets.QMessageBox.Yes:
            event.accept()
        else:
            event.ignore()

    def selecReunion(self):
        if self.wReunion is None:
            self.wReunion = Wreunion()
        self.wReunion.show()

    def selecCarrera(self):
        if self.wCarrera is None:
            self.wCarrera = Wcarrera()
        self.wCarrera.show()